// samples/vite-react-ssr-app/src/App.tsx
import HelloWorld from './components/HelloWorld.tsx'

interface AppProps {
  data?: {
    [key: string]: unknown
  }
}

export default function App({ data }: AppProps) {
  const name = (data?.name as string | undefined) ?? 'World'

  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <title>SSR with Deno</title>
      </head>
      <body>
        <div id="root">
          <HelloWorld name={name} />
          {Object.keys(data ?? {}).length > 0 && (
            <pre style={{ marginTop: '2rem', padding: '1rem', background: '#f5f5f5' }}>
              {JSON.stringify(data, null, 2)}
            </pre>
          )}
        </div>
      </body>
    </html>
  )
}

// samples/svelte-ssr-app/src/App.svelte
<script lang="ts">
  import HelloWorld from './components/HelloWorld.svelte'

  interface AppProps {
    data?: Record<string, unknown>
  }

  let { data }: AppProps = $props()
  let name = $derived((data?.name as string) ?? 'World')
</script>

<div>
  <h1>Svelte SSR with Deno</h1>
  <HelloWorld {name} />
  {#if data && Object.keys(data).length > 0}
    <pre>{JSON.stringify(data, null, 2)}</pre>
  {/if}
</div>
