// samples/vite-vue-ssr-app/src/App.vue
<template>
  <div>
    <h1>Vue SSR with Deno</h1>
    <HelloWorld :name="name" />
    <pre v-if="hasData">{{ data }}</pre>
  </div>
</template>

<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'

interface AppProps {
  data?: Record<string, unknown>
}

const props = defineProps<AppProps>()
const name = (props.data?.name as string) ?? 'World'
const hasData = props.data && Object.keys(props.data).length > 0
</script>

// samples/svelte-ssr-app/src/App.svelte
<script lang="ts">
  import HelloWorld from './components/HelloWorld.svelte'

  interface AppProps {
    data?: Record<string, unknown>
  }

  let { data }: AppProps = $props()
  let name = $derived((data?.name as string) ?? 'World')
</script>

<div>
  <h1>Svelte SSR with Deno</h1>
  <HelloWorld {name} />
  {#if data && Object.keys(data).length > 0}
    <pre>{JSON.stringify(data, null, 2)}</pre>
  {/if}
</div>
